# Generated by Django 3.2.9 on 2022-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accounts_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
