# Generated by Django 4.0.4 on 2022-10-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categories',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='client_enquery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('start_date', models.DateField(help_text='Start Date of Advertising Period')),
                ('end_date', models.DateField(help_text='End Date of Advertising Period')),
                ('adv_format', models.CharField(choices=[('post', 'Post'), ('photo', 'Photo'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=30)),
                ('categories', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(choices=[('youtube', 'Youtube'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], default='other', max_length=30)),
                ('followers', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Enqueries',
                'verbose_name_plural': 'Client Enqueries',
            },
        ),
    ]
