# Generated by Django 4.0.4 on 2022-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_categories_client_enquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_enquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='client_enquery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
