# Generated by Django 3.2.9 on 2022-09-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='influencer_profile',
            options={'verbose_name': 'Influencer Profiles', 'verbose_name_plural': 'Influencer Profiles'},
        ),
    ]
