# Generated by Django 3.2.9 on 2022-09-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_auto_20220917_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer_profile',
            name='account_name_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='influencer_profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer_profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='influencer_profile',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
