# Generated by Django 4.0.4 on 2022-10-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_auto_20220917_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTube_Channels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
