# Generated by Django 4.0.4 on 2022-10-12 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('influencer', '0005_youtube_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer_profile',
            name='Facebook_page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer_profile',
            name='Instagram_page_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencer_profile',
            name='Youtube_channel_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtube_channels',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Instagram_Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facebook_Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
