# Generated by Django 4.0.4 on 2022-10-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0007_youtubecategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YouTubeCategories',
        ),
    ]
