# Generated by Django 4.0.4 on 2022-10-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0008_delete_youtubecategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostSubscribedYTChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('uploads', models.CharField(blank=True, max_length=200, null=True)),
                ('subs', models.CharField(blank=True, max_length=200, null=True)),
                ('TotalViews', models.CharField(blank=True, max_length=2020, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
