# Generated by Django 4.0.4 on 2022-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0009_mostsubscribedytchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostsubscribedytchannel',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
