# Generated by Django 4.0.4 on 2022-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0011_mostviewedytchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostFollowedInstaPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('posts', models.CharField(blank=True, max_length=200, null=True)),
                ('followers', models.CharField(blank=True, max_length=200, null=True)),
                ('engagementRate', models.CharField(blank=True, max_length=2020, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
