# Generated by Django 4.0.4 on 2022-10-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0012_mostfollowedinstapages'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube_channels',
            name='AllVideos',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AddField(
            model_name='youtube_channels',
            name='NumberofVideos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='youtube_channels',
            name='ProfilePicLink',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='youtube_channels',
            name='Subs',
            field=models.CharField(blank=True, max_length=12323232323, null=True),
        ),
    ]
