# Generated by Django 4.0.4 on 2022-10-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0015_youtube_channels_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebook_page',
            name='ProfilePicLink',
            field=models.URLField(blank=True, max_length=20000, null=True),
        ),
        migrations.AddField(
            model_name='facebook_page',
            name='followersCount',
            field=models.CharField(blank=True, max_length=12323232323, null=True),
        ),
        migrations.AddField(
            model_name='facebook_page',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facebook_page',
            name='posts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facebook_page',
            name='postsCount',
            field=models.CharField(blank=True, max_length=50000000000000000000, null=True),
        ),
    ]
