# Generated by Django 4.1.3 on 2022-11-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0017_instagram_page_profilepiclink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer_profile',
            name='Verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
