# Generated by Django 4.1.3 on 2022-11-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0018_influencer_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer_profile',
            name='Facebook_page_category',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='influencer_profile',
            name='Instagram_page_category',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='influencer_profile',
            name='Youtube_channel_category',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='influencer_profile',
            name='Facebook_page_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='influencer_profile',
            name='Instagram_page_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='influencer_profile',
            name='Youtube_channel_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
